apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: picalc
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: __IMAGE__
